// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzaqcosrzrpbjskjwjtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6YXFjb3NyenJwYmpza2p3anRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMDk5NzMsImV4cCI6MjA1Mjc4NTk3M30._XcsqjsYa7nAg6MUnpigOTqpAEeKQrXJBtMlAQ3GGLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);